name: flutter_admin
description: 一个基于flutter的后台管理系统 - A management system based on flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cry: 1.0.4
  dio: ^4.0.0-prev3
  cupertino_icons: ^1.0.2
  charts_flutter: ^0.9.0
  flutter_custom_clippers: ^1.1.0
  font_awesome_flutter: ^9.0.0
  flutter_colorpicker: ^0.4.0
  url_launcher: ^6.0.3
  universal_html: ^2.0.7
  mime_type: ^1.0.0
  image_picker: ^0.7.3
  image_picker_for_web: ^2.0.0
  video_player: ^2.1.0
  quiver: ^3.0.0
  global_configuration: ^2.0.0-nullsafety.0
  file_picker: ^3.0.0
  flutter_simple_treeview: ^3.0.0-nullsafety.1
  get: ^4.0.0-nullsafety.2
  get_storage: ^2.0.1
  syncfusion_flutter_charts: ^18.4.43+1
  syncfusion_flutter_datagrid: ^18.4.30-beta
  flutter_markdown: ^0.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0

dependency_overrides:
  intl: 0.17.0

flutter:
  uses-material-design: true
  assets:
    - config/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
    - family: RockSalt
      fonts:
        - asset: assets/fonts/RockSalt-Regular.ttf
    - family: Bradhitc
      fonts:
        - asset: assets/fonts/BRADHITC.TTF
    - family: OpenSansCondensed
      fonts:
        - asset: assets/fonts/OpenSansCondensed-LightItalic.TTF
    - family: Italianno
      fonts:
        - asset: assets/fonts/Italianno-Regular.TTF
    - family: BowlbyOneSC
      fonts:
        - asset: assets/fonts/BowlbyOneSC-Regular.TTF
    - family: AnnieUseYourTelescope
      fonts:
        - asset: assets/fonts/AnnieUseYourTelescope-Regular.TTF
    - family: Chango
      fonts:
        - asset: assets/fonts/Chango-Regular.TTF
    - family: Agencry
      fonts:
        - asset: assets/fonts/AGENCYR.TTF

flutter_intl:
  enabled: true
